begin;
create extension if not exists pgcrypto;
do $$ begin create type user_role as enum ('admin','member'); exception when duplicate_object then null; end $$;
do $$ begin create type task_status as enum ('todo','in_progress','done','undefined'); exception when duplicate_object then null; end $$;
create table if not exists teams (id serial primary key,name text not null unique,created_at timestamptz default now());
create table if not exists users (id serial primary key,full_name text,username text not null unique,email text not null unique,password_hash text not null,avatar_path text,created_at timestamptz default now());
create table if not exists user_profiles (id uuid primary key references auth.users(id) on delete cascade,username text not null unique,team_id int references teams(id),role user_role not null default 'member',bio text,avatar_url text,created_at timestamptz default now());
create table if not exists projects (id serial primary key,creator_user_id int references users(id) on delete set null,project_name text not null,description text,created_at timestamptz default now(),project_logo text,project_cover text,todo_count int not null default 0,in_progress_count int not null default 0,done_count int not null default 0,undefined_count int not null default 0,team_access_id int references teams(id));
do $$ begin alter table projects add constraint uq_projects_creator_name unique (creator_user_id, project_name); exception when duplicate_object then null; end $$;
alter table projects alter column description set default 'a brief of how i wanna change the world!';
alter table projects add column if not exists project_logo text;
alter table projects add column if not exists project_cover text;
alter table projects add column if not exists creator_user_id int;
alter table projects add column if not exists project_name text;
alter table projects add column if not exists team_access_id int;
do $$ begin alter table projects add constraint fk_projects_creator_user foreign key (creator_user_id) references users(id) on delete set null; exception when duplicate_object then null; end $$;
do $$ begin alter table projects add constraint fk_projects_team_access foreign key (team_access_id) references teams(id); exception when duplicate_object then null; end $$;
do $$ begin if exists(select 1 from information_schema.columns where table_name='projects' and column_name='name') then execute 'update projects set project_name = name where project_name is null'; end if; end $$;
create or replace function hash_password_if_needed() returns trigger as $$ begin if new.password_hash is null then return new; end if; if new.password_hash = 'GOOGLE_AUTH' then return new; end if; if new.password_hash ~ '^[0-9a-f]{64}$' then return new; end if; new.password_hash := encode(digest(new.password_hash, 'sha256'), 'hex'); return new; end $$ language plpgsql;
drop trigger if exists trg_hash_password on users;
create trigger trg_hash_password before insert or update on users for each row execute function hash_password_if_needed();
create or replace function sync_project_task_counts() returns trigger as $$ declare pid int; begin pid := coalesce(new.project_id, old.project_id); if pid is null then return null; end if; perform set_config('myapp.allow_project_counts_update','true',true); update projects p set todo_count = (select count(*) from tasks where project_id = pid and status = 'todo'), in_progress_count = (select count(*) from tasks where project_id = pid and status = 'in_progress'), done_count = (select count(*) from tasks where project_id = pid and status = 'done'), undefined_count = (select count(*) from tasks where project_id = pid and status = 'undefined') where p.id = pid; return null; end $$ language plpgsql;
drop trigger if exists trg_sync_project_counts on tasks;
create trigger trg_sync_project_counts after insert or update or delete on tasks for each row execute function sync_project_task_counts();
create or replace function block_project_counts_manual_update() returns trigger as $$ begin if current_setting('myapp.allow_project_counts_update', true) = 'true' then return new; end if; if new.todo_count <> old.todo_count or new.in_progress_count <> old.in_progress_count or new.done_count <> old.done_count or new.undefined_count <> old.undefined_count then raise exception 'Project status counters are managed by tasks changes only'; end if; return new; end $$ language plpgsql;
drop trigger if exists trg_block_project_counts on projects;
create trigger trg_block_project_counts before update on projects for each row execute function block_project_counts_manual_update();
alter table user_profiles enable row level security;
alter table projects enable row level security;
alter table tasks enable row level security;
do $$ begin create policy "Owner can manage own profile" on user_profiles for all using (id = auth.uid()) with check (id = auth.uid()); exception when duplicate_object then null; end $$;
do $$ begin create policy "Team members can view projects" on projects for select using (team_access_id in (select team_id from user_profiles where id = auth.uid()) or creator_user_id in (select u.id from users u join user_profiles up on up.username = u.username where up.id = auth.uid())); exception when duplicate_object then null; end $$;
do $$ begin create policy "Team members can modify projects" on projects for all using (team_access_id in (select team_id from user_profiles where id = auth.uid())) with check (team_access_id in (select team_id from user_profiles where id = auth.uid())); exception when duplicate_object then null; end $$;
do $$ begin create policy "Team members can access tasks" on tasks for all using (project_id in (select p.id from projects p join user_profiles up on up.team_id = p.team_access_id where up.id = auth.uid())) with check (project_id in (select p.id from projects p join user_profiles up on up.team_id = p.team_access_id where up.id = auth.uid())); exception when duplicate_object then null; end $$;
create index if not exists idx_tasks_project_status on tasks (project_id, status);
create index if not exists idx_projects_creator on projects (creator_user_id);
create index if not exists idx_projects_team_access on projects (team_access_id);
create index if not exists idx_user_profiles_team on user_profiles (team_id);
commit;
